-- License CC0 (Creative Commons license) (c) darkfrei, 2022

local easy = require ('easy')

function love.load()
	
	easy:load ()
	
	easy:newObject ({x=650/2, y=650-50/2, w=650, h=50, color={0.28, 0.63, 0.05}, oColor={0.15, 0.3, 0}})
	ball = easy:newObject ({x=650/2, y=650/2, r=20, re=0.9, type="dynamic", color={0.76, 0.18, 0.05}, oColor={0.4, 0.1, 0}})
	easy:newObject ({x=200, y=550, w=20, h=100, de=5, type="dynamic", color={0.20, 0.20, 0.20}, oColor={0.1, 0.1, 0}})
	easy:newObject ({x=200, y=400, w=100, h=20, de=2, type="dynamic", color={0.20, 0.20, 0.20}, oColor={0.1, 0.1, 0}})

  -- initial graphics setup
  -- set the background color to a nice blue
  love.graphics.setBackgroundColor(0.41, 0.53, 0.97)
  love.window.setMode(650, 650) -- set the window dimensions to 650 by 650
end


function love.update(dt)
	easy:update (dt)

	-- here we are going to create some keyboard events
	-- press the right arrow key to push the ball to the right
	if love.keyboard.isDown("right") then
		ball.body:applyForce(400, 0)
	-- press the left arrow key to push the ball to the left
	elseif love.keyboard.isDown("left") then
		ball.body:applyForce(-400, 0)
	-- press the up arrow key to set the ball in the air
	elseif love.keyboard.isDown("down") then
		ball.body:applyForce(0, 800)
	elseif love.keyboard.isDown("up") then
		ball.body:setPosition(650/2, 650/2)
	-- we must set the velocity to zero to prevent a potentially large
	-- velocity generated by the change in position
		ball.body:setLinearVelocity(0, 0)
  end
end

function love.draw()
	easy:draw ()
	
--	points
	love.graphics.setColor (1,1,1)
	love.graphics.points (650/2,650-50/2, 650/2,650/2, 200,550, 200,400)
end

function love.keypressed(key, scancode, isrepeat)
	if false then
	elseif key == "escape" then
		love.event.quit()
	end
end

function love.mousepressed( x, y, button, istouch, presses )
	if button == 1 then -- left mouse button
	elseif button == 2 then -- right mouse button
	end
end

function love.mousemoved( x, y, dx, dy, istouch )
end

function love.mousereleased( x, y, button, istouch, presses )
	if button == 1 then -- left mouse button
	elseif button == 2 then -- right mouse button
	end
end