-- generated by intersection editor
-- do not edit manually

return {
	ways = {
		{
			tags = {
				curve = "linear",
				type = "in",
				layer = "0",
			},
			id = 1,
			nodeRefs = {
				"1",
				"2",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "out",
				layer = "0",
			},
			id = 2,
			nodeRefs = {
				"4",
				"5",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "in",
				layer = "0",
			},
			id = 3,
			nodeRefs = {
				"6",
				"7",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "out",
				layer = "0",
			},
			id = 4,
			nodeRefs = {
				"9",
				"10",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "in",
				layer = "0",
			},
			id = 5,
			nodeRefs = {
				"11",
				"12",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "out",
				layer = "0",
			},
			id = 6,
			nodeRefs = {
				"14",
				"15",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "in",
				layer = "0",
			},
			id = 7,
			nodeRefs = {
				"16",
				"17",
			},
		},
		{
			tags = {
				curve = "linear",
				type = "out",
				layer = "0",
			},
			id = 8,
			nodeRefs = {
				"19",
				"20",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "out",
			},
			id = 9,
			nodeRefs = {
				"53",
				"54",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "in",
			},
			id = 10,
			nodeRefs = {
				"55",
				"56",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "out",
			},
			id = 11,
			nodeRefs = {
				"57",
				"58",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "in",
			},
			id = 12,
			nodeRefs = {
				"59",
				"60",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "out",
			},
			id = 13,
			nodeRefs = {
				"61",
				"62",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "in",
			},
			id = 14,
			nodeRefs = {
				"63",
				"64",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "in",
			},
			id = 15,
			nodeRefs = {
				"65",
				"66",
			},
		},
		{
			tags = {
				curve = "linear",
				layer = "0",
				type = "out",
			},
			id = 16,
			nodeRefs = {
				"67",
				"68",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 17,
			nodeRefs = {
				"76",
				"77",
				"69",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 18,
			nodeRefs = {
				"69",
				"78",
				"79",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 19,
			nodeRefs = {
				"79",
				"80",
				"71",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 20,
			nodeRefs = {
				"71",
				"81",
				"72",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 21,
			nodeRefs = {
				"72",
				"82",
				"73",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 22,
			nodeRefs = {
				"73",
				"83",
				"74",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 23,
			nodeRefs = {
				"74",
				"84",
				"75",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 24,
			nodeRefs = {
				"75",
				"87",
				"76",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 25,
			nodeRefs = {
				"2",
				"88",
				"74",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 26,
			nodeRefs = {
				"74",
				"89",
				"53",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 27,
			nodeRefs = {
				"56",
				"90",
				"75",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 28,
			nodeRefs = {
				"75",
				"91",
				"14",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 29,
			nodeRefs = {
				"17",
				"92",
				"76",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 30,
			nodeRefs = {
				"76",
				"93",
				"57",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 31,
			nodeRefs = {
				"60",
				"94",
				"69",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 32,
			nodeRefs = {
				"69",
				"95",
				"4",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 33,
			nodeRefs = {
				"7",
				"96",
				"79",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 34,
			nodeRefs = {
				"79",
				"97",
				"61",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 35,
			nodeRefs = {
				"64",
				"98",
				"71",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 36,
			nodeRefs = {
				"71",
				"99",
				"19",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 37,
			nodeRefs = {
				"12",
				"100",
				"72",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 38,
			nodeRefs = {
				"72",
				"101",
				"67",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 39,
			nodeRefs = {
				"66",
				"102",
				"73",
			},
		},
		{
			tags = {
				curve = "bezier",
				layer = "0",
			},
			id = 40,
			nodeRefs = {
				"73",
				"103",
				"9",
			},
		},
	},
	nodes = {
		["91"] = {
			y = 477,
			x = 625,
		},
		["92"] = {
			y = 590,
			x = 624,
		},
		["93"] = {
			y = 686,
			x = 689,
		},
		["94"] = {
			y = 794,
			x = 809,
		},
		["95"] = {
			y = 822,
			x = 924,
		},
		["96"] = {
			y = 843,
			x = 995,
		},
		["97"] = {
			y = 792,
			x = 1099,
		},
		["98"] = {
			y = 712,
			x = 1174,
		},
		["6"] = {
			y = 1140,
			x = 990,
		},
		["1"] = {
			y = -60,
			x = 930,
		},
		["7"] = {
			y = 940,
			x = 990,
		},
		["99"] = {
			y = 574,
			x = 1261,
		},
		["100"] = {
			y = 491,
			x = 1262,
		},
		["101"] = {
			y = 329,
			x = 1231,
		},
		["16"] = {
			y = 570,
			x = 360,
		},
		["103"] = {
			y = 201,
			x = 1018,
		},
		["17"] = {
			y = 570,
			x = 560,
		},
		["20"] = {
			y = 570,
			x = 1560,
		},
		["15"] = {
			y = 510,
			x = 360,
		},
		["4"] = {
			y = 940,
			x = 930,
		},
		["14"] = {
			y = 510,
			x = 560,
		},
		["2"] = {
			y = 140,
			x = 930,
		},
		["5"] = {
			y = 1140,
			x = 930,
		},
		["12"] = {
			y = 510,
			x = 1360,
		},
		["11"] = {
			y = 510,
			x = 1560,
		},
		["102"] = {
			y = 233,
			x = 1140,
		},
		["10"] = {
			y = -60,
			x = 990,
		},
		["9"] = {
			y = 140,
			x = 990,
		},
		["19"] = {
			y = 570,
			x = 1360,
		},
		["53"] = {
			y = 220,
			x = 734,
		},
		["54"] = {
			y = 47,
			x = 557,
		},
		["55"] = {
			y = 121,
			x = 485,
		},
		["56"] = {
			y = 266,
			x = 653,
		},
		["57"] = {
			y = 757,
			x = 674,
		},
		["58"] = {
			y = 902,
			x = 492,
		},
		["59"] = {
			y = 979,
			x = 557,
		},
		["60"] = {
			y = 813,
			x = 748,
		},
		["61"] = {
			y = 811,
			x = 1147,
		},
		["62"] = {
			y = 949,
			x = 1301,
		},
		["63"] = {
			y = 875,
			x = 1367,
		},
		["64"] = {
			y = 757,
			x = 1186,
		},
		["65"] = {
			y = -18,
			x = 1382,
		},
		["66"] = {
			y = 199,
			x = 1202,
		},
		["67"] = {
			y = 273,
			x = 1289,
		},
		["68"] = {
			y = 78,
			x = 1480,
		},
		["69"] = {
			y = 781,
			x = 894,
		},
		["71"] = {
			y = 618,
			x = 1200,
		},
		["72"] = {
			y = 430,
			x = 1221,
		},
		["73"] = {
			y = 235,
			x = 1063,
		},
		["74"] = {
			y = 247,
			x = 857,
		},
		["75"] = {
			y = 405,
			x = 664,
		},
		["76"] = {
			y = 636,
			x = 678,
		},
		["77"] = {
			y = 755,
			x = 741,
		},
		["78"] = {
			y = 793,
			x = 964,
		},
		["79"] = {
			y = 782,
			x = 1040,
		},
		["80"] = {
			y = 747,
			x = 1172,
		},
		["81"] = {
			y = 537,
			x = 1234,
		},
		["82"] = {
			y = 309,
			x = 1191,
		},
		["83"] = {
			y = 204,
			x = 972,
		},
		["84"] = {
			y = 300,
			x = 745,
		},
		["87"] = {
			y = 513,
			x = 627,
		},
		["88"] = {
			y = 196,
			x = 906,
		},
		["89"] = {
			y = 247,
			x = 794,
		},
		["90"] = {
			y = 328,
			x = 671,
		},
	},
}
