-- core/exporter.lua
-- graph export module for saving road network as lua configuration

local Exporter = {}

local function serialize(tbl, indent)
	indent = indent or 0

	local pad = string.rep("    ", indent)
	local nextPad = string.rep("    ", indent + 1)

	if type(tbl) ~= "table" then
		if type(tbl) == "string" then
			return string.format("%q", tbl)
		end
		return tostring(tbl)
	end

	local result = "{\n"

	-- check if table is array-like
	local isArray = true
	local expected = 1

	for k, _ in pairs(tbl) do
		if k ~= expected then
			isArray = false
			break
		end
		expected = expected + 1
	end

	if isArray then
		local i = 1
		while tbl[i] ~= nil do
			result = result
			.. nextPad
			.. serialize(tbl[i], indent + 1)
			.. ",\n"
			i = i + 1
		end
	else
		for k, v in pairs(tbl) do
			local key = (type(k) == "string" and k:match("^%a[%w_]*$"))
			and k
			or "[" .. serialize(k, 0) .. "]"

			result = result
			.. nextPad
			.. key
			.. " = "
			.. serialize(v, indent + 1)
			.. ",\n"
		end
	end

	return result .. pad .. "}"
end

function Exporter.exportLua(map, filename)
	filename = filename or "output.lua"

	local exportData = {
		nodes = map.nodes,
		ways = map.ways
	}

	local content =
	"-- generated by intersection network editor\n"
	.. "return " .. serialize(exportData, 0) .. "\n"

	love.filesystem.write(filename, content)

	return true
end

return Exporter