-- editor/exporter.lua
-- stable graph exporter for intersection editor
-- preserves node ids and keeps control points correctly structured

local Exporter = {}

local function serialize(tbl, indent)
	indent = indent or 0
	local pad = string.rep("    ", indent)
	local nextPad = string.rep("    ", indent + 1)

	if type(tbl) ~= "table" then
		if type(tbl) == "string" then
			return string.format("%q", tbl)
		end
		return tostring(tbl)
	end

	local result = "{\n"
	local isArray = true
	local expected = 1

	for k, _ in pairs(tbl) do
		if k ~= expected then
			isArray = false
			break
		end
		expected = expected + 1
	end

	if isArray then
		local i = 1
		while tbl[i] ~= nil do
			result = result .. nextPad .. serialize(tbl[i], indent + 1) .. ",\n"
			i = i + 1
		end
	else
		for k, v in pairs(tbl) do
			local key
			if type(k) == "string" and k:match("^%a[%w_]*$") then
				key = k
			else
				key = "[" .. serialize(k, 0) .. "]"
			end
			result = result .. nextPad .. key .. " = " .. serialize(v, indent + 1) .. ",\n"
		end
	end

	result = result .. pad .. "}"
	return result
end

local function normalizeNodes(nodes)
	local out = {}
	for id, node in pairs(nodes) do
		-- preserve numeric keys as numbers
		local key = tonumber(id) or id
		out[key] = {
			x = math.floor(node.x + 0.5),
			y = math.floor(node.y + 0.5)
		}
	end
	return out
end

local function normalizeWays(ways)
	local out = {}
	for _, way in ipairs(ways) do
		local refs = {}
		for _, ref in ipairs(way.nodeRefs) do
			-- preserve numeric refs as numbers
			table.insert(refs, tonumber(ref) or ref)
		end

		if #refs >= 2 then
			-- copy tags as-is, preserving original types
			local tags = {}
			if way.tags then
				for k, v in pairs(way.tags) do
					tags[k] = v
				end
			end

			table.insert(out, {
					-- preserve string ids (e.g. "N-IN"), only fall back to number
					id       = (type(way.id) == "string" and way.id) or tonumber(way.id) or #out + 1,
					nodeRefs = refs,
					tags     = tags
				})
		end
	end
	return out
end

local function validate(map)
	if type(map) ~= "table" then
		return false, "map is not a table"
	end
	if type(map.nodes) ~= "table" then
		return false, "map.nodes missing"
	end
	if type(map.ways) ~= "table" then
		return false, "map.ways missing"
	end
	return true
end

function Exporter.buildLua(map)
	local ok, err = validate(map)
	if not ok then
		return nil, err
	end

	local exportData = {
		nodes = normalizeNodes(map.nodes),
		ways  = normalizeWays(map.ways)
	}

	local content =
	"-- generated by intersection editor\n" ..
	"-- do not edit manually\n\n" ..
	"return " .. serialize(exportData, 0) .. "\n"

	return content
end

function Exporter.exportLua(map, filename)
	filename = filename or "output.lua"

	local ok, err = validate(map)
	if not ok then
		return false, err
	end

	local exportData = {
		nodes = normalizeNodes(map.nodes),
		ways  = normalizeWays(map.ways)
	}

	local content =
	"-- generated by intersection editor\n" ..
	"-- do not edit manually\n\n" ..
	"return " .. serialize(exportData, 0) .. "\n"

	local file = love.filesystem.newFile(filename, "w")
	if not file then
		return false, "cannot open output target file"
	end

	file:write(content)
	file:close()
	return true
end

return Exporter